
CREATE TABLE users(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user TEXT NOT NULL,
	name TEXT NOT NULL,
	unit TEXT NOT NULL,
	hash TEXT NOT NULL,
	admin INTEGER DEFAULT 0,
	enabled INTEGER DEFAULT 1,
	CONSTRAINT user UNIQUE(user) 
);

CREATE TABLE activity (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	start TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	end TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	user INTEGER NOT NULL,
	samples INTEGER DEFAULT 0,
	FOREIGN KEY (user) REFERENCES users (id)
);

CREATE TABLE settings (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	key TEXT,
	value TEXT,
	CONSTRAINT key UNIQUE(key)
);


insert into users (user,name,unit,hash,admin) VALUES ('brunocosta','Bruno Costa','Forestbiotech','d66428edfec8451d3ff70e09b678af4df479a1903b5e96864c36839cc6241324',1);